---
- name: Include adams config
  sudo: True
  lineinfile:
    dest: /etc/auto.master
    regexp: '/etc/auto.adams$'
    line: '/- /etc/auto.adams'
  notify:
    - Restart autofs

- name: Install adams config
  sudo: True
  copy: src=roles/autofs_client/files/auto.adams dest=/etc/auto.adams owner=root group=root mode=0644
  notify:
    - Restart autofs
