- hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ansible_os_family}}

- name: Default provisioning task
  hosts: all
  gather_facts: False

  roles:
    - install_packages
    - git
    - java
    - golang
    - rvm
    - nodejs
    - postgresql
    - vim
    - docker
    - google_chrome
    - hipchat
    - user_config
    - lilyterm
    - gnome_terminal
    - virtualbox
    #- autofs_client

- name: Ping hosts
  hosts: ping
  gather_facts: False

  roles:
    - ping
