---
- stat: path=/usr/bin/VBoxManage
  register: vbox

- name: virtualbox apt repository key
  become: True
  when: not vbox.stat.exists
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox.asc

- name: Add virtualbox GPG key
  become: True
  when: not vbox.stat.exists
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys 7B0FAB3A13B907435925D9C954422A4B98AB5139

- name: virtualbox apt repository
  become: True
  when: not vbox.stat.exists
  apt_repository: repo="deb http://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib" state=present update_cache=yes

- name: install virtualbox
  become: True
  when: not vbox.stat.exists
  apt: name=virtualbox state=latest update_cache=yes cache_valid_time=600

- name: Add keyfile section to NetworkManager.conf
  become: True
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: '\[keyfile\]'
    line: '[keyfile]'

- name: Add unmanaged vboxnet0 to NetworkManager.conf
  become: True
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    insertafter: '\[keyfile\]'
    regexp: 'unmanaged-devices='
    line: 'unmanaged-devices=interface-name:vboxnet0'
