---
- name: Install default packages
  sudo: True
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - unzip
    - wget
    - curl
    - mercurial
    - software-properties-common
    - openssh-client
    - openssh-server
    - exuberant-ctags
    - cscope
    - apt-transport-https
    - postgresql
    - libpq-dev
    - redis-server
    - compton
    - tofrodos
    - rdesktop
    - keepass2
    - xdotool
    - clipit

- stat: path=/usr/bin/node
  register: nodejs

- name: Add node repo
  sudo: True
  when: not nodejs.stat.exists
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: Install node
  sudo: True
  apt: name=nodejs state=latest

- stat: path=/usr/bin/coffee
  register: coffeescript

- name: Install coffeescript
  sudo: True
  when: not coffeescript.stat.exists
  shell: npm install -g coffee-script

- stat: path=/usr/bin/coffeelint
  register: coffeelint

- name: Install coffeelint
  sudo: True
  when: not coffeelint.stat.exists
  shell: npm install -g coffeelint
