---
- name: Install default packages
  sudo: True
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - unzip
    - wget
    - curl
    - screen
    - traceroute
    - mercurial
    - software-properties-common
    - openssh-client
    - openssh-server
    - ntp
    - exuberant-ctags
    - cscope
    - apt-transport-https
    - redis-server
    - autofs
    - tofrodos
    - python-pip
    - compton #compositing manager for lightweight desktops like openbox, xfce, etc.
    - x11vnc
    - rdesktop
    - xtightvncviewer
    - ssvnc
    - keepass2
    - xdotool
    - gimp
    - mplayer2
    - silversearcher-ag #faster grep
    - libreoffice
    - asunder #music CD ripper
    - picard #rename/tag mp3 files based on online signatures
    #also need https://git.lekensteyn.nl/ltunify/
    #also included at some point but no longer use
    #- clipit #view clipboard history
    #- compiz-plugins-extra #original alt-tab application switcher
