---
- name: Install default packages
  sudo: True
  apt: name={{item}} state=latest
  with_items:
    - build-essential
    - unzip
    - wget
    - curl
    - screen
    - traceroute
    - mercurial
    - software-properties-common
    - openssh-client
    - openssh-server
    - exuberant-ctags
    - cscope
    - apt-transport-https
    - postgresql
    - libpq-dev
    - redis-server
    - autofs
    - tofrodos
    - compton
    - x11vnc
    - rdesktop
    - xtightvncviewer
    - ssvnc
    - keepass2
    - xdotool
    - clipit
    - gimp
    - mplayer2
    - silversearcher-ag
    - libreoffice
    - usb-creator-gtk
    - asunder
    - picard
