---
- name: Install default packages
  sudo: True
  apt: name={{item}} state=latest
  with_items:
    - unzip
    - wget
    - curl
    - git
    - software-properties-common
    - openssh-client
    - exuberant-ctags
    - cscope
    - apt-transport-https

- stat: path=/usr/bin/node
  register: nodejs

- name: Add node repo
  sudo: True
  when: not nodejs.stat.exists
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -

- name: Install node
  sudo: True
  apt: name=nodejs state=latest

- stat: path=/usr/bin/coffee
  register: coffeescript

- name: Install coffeescript
  sudo: True
  when: not coffeescript.stat.exists
  shell: npm install -g coffee-script

- stat: path=/usr/bin/coffeelint
  register: coffeelint

- name: Install coffeelint
  sudo: True
  when: not coffeelint.stat.exists
  shell: npm install -g coffeelint

- stat: path=~/.gitconfig
  register: gitconfig

- name: Configure git
  when: not gitconfig.stat.exists
  shell: git config --global user.email "garton.tim@gmail.com" && git config --global user.name "Tim Garton" && git config --global push.default simple
