---
- name: Set HISTSIZE
  lineinfile:
    dest: ~/.bashrc
    regexp: 'HISTSIZE=.*$'
    line: 'HISTSIZE=-1'

- name: Set HISTFILESIZE
  lineinfile:
    dest: ~/.bashrc
    regexp: 'HISTFILESIZE=.*$'
    line: 'HISTFILESIZE=-1'

- name: Set HISTTIMEFORMAT
  lineinfile:
    dest: ~/.bashrc
    regexp: 'HISTTIMEFORMAT=.*$'
    line: 'HISTTIMEFORMAT="%F %T "'

- name: Set PROMPT_COMMAND
  lineinfile:
    dest: ~/.bashrc
    regexp: 'export PROMPT_COMMAND=.*$'
    line: 'export PROMPT_COMMAND="history -a" #flush history after every command'

- name: Create goenv alias
  lineinfile:
    dest: ~/.bashrc
    regexp: ^alias goenv=.*
    line: alias goenv='env GO15VENDOREXPERIMENT=1 GOPATH=$(cd ../../../.. && pwd):$(pwd)/Godeps/_workspace'

# Not sure this is actually necessary
- name: Export HISTFILESIZE HISTSIZE HISTTIMEFORMAT
  lineinfile: dest=~/.bashrc line='export HISTFILESIZE HISTSIZE HISTTIMEFORMAT'

- name: Add git doglog
  shell: git config --global alias.doglog "log --graph --pretty=format:'%h -%C(yellow)%d%Creset %C(bold white)%s%Creset %Cgreen(%cd) %C(bold blue)<%an>%Creset' --date=iso"
