---
- stat: path=/usr/bin/docker
  register: docker

- name: Install docker
  sudo: True
  when: not docker.stat.exists
  shell: curl -sSL https://get.docker.com/ubuntu/ | sudo sh

- name: Add tim to docker group
  sudo: True
  when: not docker.stat.exists
  user: name=tim groups=docker append=yes

- name: Add tim to docker group
  sudo: True
  when: not docker.stat.exists
  service: name=docker state=restarted
